# implicitly
disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- todo
- legacy_constructor
- vertical_parameter_alignment
- syntactic_sugar
- implicit_getter
- redundant_optional_initialization
- shorthand_operator
- multiple_closures_with_trailing_closure
#- weak_computed_property
- force_cast
- switch_case_alignment
- comment_spacing
- legacy_random
- identifier_name
- unneeded_override
- redundant_string_enum_value

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- Carthage

large_tuple: 5

identifier_name:
    min_length: 2


cyclomatic_complexity:
    warning: 25
    error: 35

function_body_length:
    warning: 60
    error: 100

type_body_length:
    warning: 400
    error: 500

line_length:
    warning: 400
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

file_length:
    warning: 700
    error: 900
    ignore_comment_only_lines: true

function_parameter_count:
    warning: 8
    error: 10

opt_in_rules: # some rules are only opt-in
#- force_unwrapping
- empty_count
- empty_string

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

# more rules
#https://realm.github.io/SwiftLint/rule-directory.html
#https://medium.com/developerinsider/how-to-use-swiftlint-with-xcode-to-enforce-swift-style-and-conventions-368e49e910
#https://github.com/realm/SwiftLint/blob/main/.swiftlint.yml
