# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
target 'SwiftStarterApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'Kingfisher'
  pod 'DropDown'
  pod 'SwiftLint'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  # Pods for SwiftStarterApp

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
